
export const CHECK_HISTORIES = Symbol('CHECK_HISTORIES');
export const CHANGE_HISTORY_FILTER = Symbol('CHANGE_HISTORY_FILTER');
// export const SET_HISTORY_FIELD = Symbol('SET_HISTORY_FIELD');
export const TOGGLE_HISTORY_FILTER = Symbol('TOGGLE_HISTORY_FILTER');
export const REFETCH_HISTORIES = Symbol('REFETCH_HISTORIES');
export const CLEAR_HISTORY_FILTER = Symbol('CLEAR_HISTORY_FILTER');
export const UPDATE_HISTORY_GRID_PAGINATION = Symbol('UPDATE_HISTORY_GRID_PAGINATION');
export const CHANGE_HISTORY_GRID_SORTORDER = Symbol('CHANGE_HISTORY_GRID_SORTORDER');
export const FETCH_HISTORIES = Symbol('FETCH_HISTORIES');
export const SELECT_HISTORY = Symbol('SELECT_HISTORY');
export const GET_EVENT_DETAILS = Symbol('GET_EVENT_DETAILS');
export const UPDATE_FILTER_ERRORS = Symbol('UPDATE_FILTER_ERRORS');
export const CHANGE_HISTORY_PROFILE = Symbol('CHANGE_HISTORY_PROFILE');
