export const CORE_ITEM_TRANSLATION_FETCH = Symbol('CORE_ITEM_TRANSLATION_FETCH');
export const SET_PERMISSIONS = Symbol('SET_PERMISSIONS');
export const CHECK_PERMISSION = Symbol('CHECK_PERMISSION');
